-- 회원, 로그인, 이메일 인증코드, 사무소, 사업자 인증 신청, 문서 이동 outbox, 사무소 소속

CREATE TABLE member (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    display_name        VARCHAR(20)   NOT NULL,
    email                VARCHAR(255)  NOT NULL,
    profile_image_url    VARCHAR(500),
    account_status       VARCHAR(10)   NOT NULL DEFAULT 'ACTIVE'
                          CHECK (account_status IN ('ACTIVE','SUSPENDED','WITHDRAWN')),
    created_at           TIMESTAMPTZ   NOT NULL DEFAULT now(),
    withdrawn_at         TIMESTAMPTZ
);

ALTER TABLE member ADD CONSTRAINT ck_member_withdrawn
    CHECK ((account_status = 'WITHDRAWN') = (withdrawn_at IS NOT NULL));

CREATE UNIQUE INDEX uq_member_email_active
    ON member (email)
    WHERE account_status != 'WITHDRAWN';

COMMENT ON TABLE member IS '회원';
COMMENT ON COLUMN member.id IS '회원 내부 식별자';
COMMENT ON COLUMN member.display_name IS '서비스에서 표시하는 회원 이름';
COMMENT ON COLUMN member.email IS '알림·재인증 코드 수신에 쓰는 가입·연락 이메일(로그인 수단과는 독립)';
COMMENT ON COLUMN member.profile_image_url IS '프로필 이미지 URL';
COMMENT ON COLUMN member.account_status IS '회원 계정 상태: ACTIVE 정상, SUSPENDED 이용 제한, WITHDRAWN 탈퇴';
COMMENT ON COLUMN member.created_at IS '회원 레코드 생성 일시';
COMMENT ON COLUMN member.withdrawn_at IS '탈퇴 처리 일시. WITHDRAWN 상태가 아니면 NULL';

CREATE TABLE login_identity (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    member_id     BIGINT       NOT NULL REFERENCES member(id) ON DELETE RESTRICT,
    provider      VARCHAR(10)  NOT NULL CHECK (provider IN ('KAKAO','EMAIL')),
    provider_key  VARCHAR(255) NOT NULL,
    created_at    TIMESTAMPTZ  NOT NULL DEFAULT now(),
    revoked_at    TIMESTAMPTZ
);

CREATE UNIQUE INDEX uq_login_identity_active
    ON login_identity (provider, provider_key)
    WHERE revoked_at IS NULL;

COMMENT ON TABLE login_identity IS '로그인 수단(카카오·이메일 연결 정보)';
COMMENT ON COLUMN login_identity.id IS '로그인 수단 내부 식별자';
COMMENT ON COLUMN login_identity.member_id IS '이 로그인 수단을 소유한 회원';
COMMENT ON COLUMN login_identity.provider IS '로그인 제공자: KAKAO 또는 EMAIL';
COMMENT ON COLUMN login_identity.provider_key IS '카카오 고유 회원번호, 또는 정규화(소문자)된 이메일';
COMMENT ON COLUMN login_identity.created_at IS '연결 생성 일시';
COMMENT ON COLUMN login_identity.revoked_at IS '연결 해제(탈퇴) 일시. soft delete — 하드 삭제하지 않음';

CREATE TABLE login_history (
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    member_id          BIGINT      NOT NULL REFERENCES member(id) ON DELETE RESTRICT,
    login_identity_id  BIGINT      REFERENCES login_identity(id) ON DELETE RESTRICT,
    ip_address         INET,
    user_agent         VARCHAR(500),
    is_new_device      BOOLEAN     NOT NULL DEFAULT false,
    created_at         TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX ix_login_history_member_created ON login_history (member_id, created_at DESC);

COMMENT ON TABLE login_history IS '로그인 시도 기록';
COMMENT ON COLUMN login_history.id IS '로그인 기록 내부 식별자';
COMMENT ON COLUMN login_history.member_id IS '로그인한 회원';
COMMENT ON COLUMN login_history.login_identity_id IS '사용된 로그인 수단';
COMMENT ON COLUMN login_history.ip_address IS '로그인 요청 IP(IPv4/IPv6 모두 저장 가능한 INET)';
COMMENT ON COLUMN login_history.user_agent IS '로그인 요청 User-Agent 원문';
COMMENT ON COLUMN login_history.is_new_device IS '새로운 기기/환경에서의 로그인인지 여부';
COMMENT ON COLUMN login_history.created_at IS '로그인 시도 일시';

CREATE TABLE email_verification_code (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    member_id       BIGINT       REFERENCES member(id) ON DELETE SET NULL,
    purpose         VARCHAR(20)  NOT NULL CHECK (purpose IN ('SIGNUP','LOGIN','STEP_UP','EMAIL_CHANGE')),
    target_email    VARCHAR(255) NOT NULL,
    challenge_id    UUID         NOT NULL UNIQUE,
    code_hash       VARCHAR(64)  NOT NULL,
    status          VARCHAR(10)  NOT NULL DEFAULT 'ACTIVE'
                     CHECK (status IN ('ACTIVE','VERIFIED','REPLACED','LOCKED','EXPIRED')),
    expires_at      TIMESTAMPTZ  NOT NULL,
    attempt_count   SMALLINT     NOT NULL DEFAULT 0 CHECK (attempt_count BETWEEN 0 AND 5),
    verified_at     TIMESTAMPTZ,
    invalidated_at  TIMESTAMPTZ,
    created_at      TIMESTAMPTZ  NOT NULL DEFAULT now()
);

ALTER TABLE email_verification_code ADD CONSTRAINT ck_email_verification_status CHECK (
    (status = 'ACTIVE' AND verified_at IS NULL AND invalidated_at IS NULL)
    OR (status = 'VERIFIED' AND verified_at IS NOT NULL AND invalidated_at IS NULL)
    OR (status IN ('REPLACED','LOCKED','EXPIRED') AND verified_at IS NULL AND invalidated_at IS NOT NULL)
);

CREATE UNIQUE INDEX uq_email_verification_active
    ON email_verification_code (target_email, purpose)
    WHERE status = 'ACTIVE';

COMMENT ON TABLE email_verification_code IS '이메일 인증코드(6자리) 발급·검증 기록';
COMMENT ON COLUMN email_verification_code.id IS '인증코드 내부 식별자';
COMMENT ON COLUMN email_verification_code.member_id IS '가입 인증처럼 회원 생성 전 발급된 경우 NULL 가능';
COMMENT ON COLUMN email_verification_code.purpose IS '인증 목적: SIGNUP 가입, LOGIN 로그인, STEP_UP 재인증, EMAIL_CHANGE 이메일 변경';
COMMENT ON COLUMN email_verification_code.target_email IS '코드를 발송한 대상 이메일(소문자 정규화)';
COMMENT ON COLUMN email_verification_code.challenge_id IS '인증 요청 식별자. 코드 제출 시 이 값과 코드를 함께 검증해 요청 컨텍스트를 바인딩';
COMMENT ON COLUMN email_verification_code.code_hash IS 'HMAC-SHA256(pepper, challenge_id||purpose||target_email||code) 해시';
COMMENT ON COLUMN email_verification_code.status IS '코드 상태: ACTIVE 활성, VERIFIED 인증완료, REPLACED 재발급으로 무효화, LOCKED 5회 실패로 잠김, EXPIRED 만료';
COMMENT ON COLUMN email_verification_code.expires_at IS '만료 시각';
COMMENT ON COLUMN email_verification_code.attempt_count IS '오입력 시도 횟수(0~5). 5에 도달하면 LOCKED로 전환';
COMMENT ON COLUMN email_verification_code.verified_at IS '인증 완료 시각';
COMMENT ON COLUMN email_verification_code.invalidated_at IS 'REPLACED/LOCKED/EXPIRED로 무효화된 시각';
COMMENT ON COLUMN email_verification_code.created_at IS '코드 발급 일시';

CREATE TABLE office (
    id                            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name                          VARCHAR(100) NOT NULL,
    representative_name           VARCHAR(50)  NOT NULL,
    business_registration_number  VARCHAR(10)  NOT NULL UNIQUE,
    real_estate_license_number    VARCHAR(30),
    phone                         VARCHAR(20)  NOT NULL,
    address_base                  VARCHAR(200) NOT NULL,
    address_detail                VARCHAR(100),
    created_at                    TIMESTAMPTZ  NOT NULL DEFAULT now()
);

COMMENT ON TABLE office IS '사무소(부동산 중개업소)';
COMMENT ON COLUMN office.id IS '사무소 내부 식별자';
COMMENT ON COLUMN office.name IS '사무소 이름';
COMMENT ON COLUMN office.representative_name IS '대표자 이름';
COMMENT ON COLUMN office.business_registration_number IS '사업자등록번호(정규화, 사무소당 고유)';
COMMENT ON COLUMN office.real_estate_license_number IS '공인중개사 등록번호';
COMMENT ON COLUMN office.phone IS '사무소 대표 연락처';
COMMENT ON COLUMN office.address_base IS '사무소 기본 주소';
COMMENT ON COLUMN office.address_detail IS '사무소 상세 주소';
COMMENT ON COLUMN office.created_at IS '사무소 생성 일시(사업자 인증 승인 시점)';

CREATE TABLE office_registration (
    id                             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    applicant_member_id            BIGINT       NOT NULL REFERENCES member(id) ON DELETE RESTRICT,
    business_registration_number   VARCHAR(10)  NOT NULL,
    status                         VARCHAR(20)  NOT NULL DEFAULT 'PENDING_VERIFICATION'
                                    CHECK (status IN ('PENDING_VERIFICATION','MANUAL_REVIEW','APPROVED','REJECTED')),
    resulting_office_id            BIGINT       REFERENCES office(id) ON DELETE RESTRICT,
    document_object_key            VARCHAR(500),
    document_original_filename     VARCHAR(255),
    document_mime_type             VARCHAR(50),
    document_size_bytes            BIGINT,
    document_etag                  VARCHAR(64),
    document_checksum_sha256       VARCHAR(64),
    document_storage_status        VARCHAR(20)
                                    CHECK (document_storage_status IN ('VERIFIED','MOVE_PENDING','PENDING_DELETION','DELETED','MOVE_FAILED')),
    rejection_reason                TEXT,
    created_at                     TIMESTAMPTZ  NOT NULL DEFAULT now(),
    reviewed_at                    TIMESTAMPTZ
);

CREATE UNIQUE INDEX uq_office_registration_result
    ON office_registration (resulting_office_id)
    WHERE resulting_office_id IS NOT NULL;

ALTER TABLE office_registration ADD CONSTRAINT ck_office_registration_status CHECK (
    (status IN ('PENDING_VERIFICATION','MANUAL_REVIEW')
        AND resulting_office_id IS NULL AND rejection_reason IS NULL AND reviewed_at IS NULL)
    OR (status = 'APPROVED'
        AND resulting_office_id IS NOT NULL AND rejection_reason IS NULL AND reviewed_at IS NOT NULL)
    OR (status = 'REJECTED'
        AND resulting_office_id IS NULL AND rejection_reason IS NOT NULL AND reviewed_at IS NOT NULL)
);

ALTER TABLE office_registration ADD CONSTRAINT ck_office_registration_storage CHECK (
    status != 'REJECTED'
    OR document_object_key IS NULL
    OR document_storage_status IN ('MOVE_PENDING','PENDING_DELETION','DELETED','MOVE_FAILED')
);

CREATE UNIQUE INDEX uq_office_registration_pending_bizno
    ON office_registration (business_registration_number)
    WHERE status IN ('PENDING_VERIFICATION','MANUAL_REVIEW');

CREATE UNIQUE INDEX uq_office_registration_pending_applicant
    ON office_registration (applicant_member_id)
    WHERE status IN ('PENDING_VERIFICATION','MANUAL_REVIEW');

CREATE INDEX ix_office_registration_bizno_status ON office_registration (business_registration_number, status);

COMMENT ON TABLE office_registration IS '사업자 인증(사무소 등록) 신청';
COMMENT ON COLUMN office_registration.id IS '신청 내부 식별자';
COMMENT ON COLUMN office_registration.applicant_member_id IS '신청자 회원';
COMMENT ON COLUMN office_registration.business_registration_number IS '신청한 사업자등록번호(정규화)';
COMMENT ON COLUMN office_registration.status IS '심사 상태: PENDING_VERIFICATION 자동검증중, MANUAL_REVIEW 수동심사중, APPROVED 승인, REJECTED 반려';
COMMENT ON COLUMN office_registration.resulting_office_id IS '승인 시 생성된 사무소(1:1, 신청당 최대 하나)';
COMMENT ON COLUMN office_registration.document_object_key IS '증빙서류 S3 객체 키';
COMMENT ON COLUMN office_registration.document_original_filename IS '증빙서류 원본 파일명(표시용, 렌더링 시 HTML escape)';
COMMENT ON COLUMN office_registration.document_mime_type IS '증빙서류 MIME 타입(서버가 확장자 기반으로 직접 매핑한 값)';
COMMENT ON COLUMN office_registration.document_size_bytes IS '증빙서류 파일 크기(바이트)';
COMMENT ON COLUMN office_registration.document_etag IS '증빙서류 S3 ETag — staging→final 복사의 CopySourceIfMatch 조건에 사용';
COMMENT ON COLUMN office_registration.document_checksum_sha256 IS 'S3 checksum 기능으로 계산한 SHA-256 — 목적지 검증 시 ETag보다 신뢰도 높은 콘텐츠 확인용';
COMMENT ON COLUMN office_registration.document_storage_status IS '증빙서류 S3 보관 상태(outbox 이동 상태머신). 문서가 아직 없으면 NULL';
COMMENT ON COLUMN office_registration.rejection_reason IS '반려 사유(길이 제한 없는 자유 서술)';
COMMENT ON COLUMN office_registration.created_at IS '신청 접수 일시';
COMMENT ON COLUMN office_registration.reviewed_at IS '심사(승인 또는 반려) 처리 일시';

CREATE TABLE office_registration_status_history (
    id                              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    office_registration_id          BIGINT      NOT NULL REFERENCES office_registration(id) ON DELETE RESTRICT,
    from_status                     VARCHAR(20) CHECK (from_status IS NULL OR from_status IN ('PENDING_VERIFICATION','MANUAL_REVIEW','APPROVED','REJECTED')),
    to_status                       VARCHAR(20) NOT NULL CHECK (to_status IN ('PENDING_VERIFICATION','MANUAL_REVIEW','APPROVED','REJECTED')),
    changed_by_type                 VARCHAR(10) NOT NULL CHECK (changed_by_type IN ('OPERATOR','SYSTEM')),
    changed_by_operator_identifier  VARCHAR(100),
    reason                          TEXT,
    created_at                      TIMESTAMPTZ NOT NULL DEFAULT now()
);

ALTER TABLE office_registration_status_history ADD CONSTRAINT ck_reg_history_actor CHECK (
    (changed_by_type = 'OPERATOR' AND changed_by_operator_identifier IS NOT NULL)
    OR (changed_by_type = 'SYSTEM' AND changed_by_operator_identifier IS NULL)
);

COMMENT ON TABLE office_registration_status_history IS '사업자 인증 신청 심사 이력';
COMMENT ON COLUMN office_registration_status_history.id IS '이력 내부 식별자';
COMMENT ON COLUMN office_registration_status_history.office_registration_id IS '대상 신청';
COMMENT ON COLUMN office_registration_status_history.from_status IS '변경 전 상태(최초 생성 시 NULL)';
COMMENT ON COLUMN office_registration_status_history.to_status IS '변경 후 상태';
COMMENT ON COLUMN office_registration_status_history.changed_by_type IS '변경 주체 유형: OPERATOR 사이로 운영자, SYSTEM 자동 처리(예: 심사 중 탈퇴에 따른 자동 반려)';
COMMENT ON COLUMN office_registration_status_history.changed_by_operator_identifier IS '운영자 식별자(현재는 GitHub 계정 또는 운영 이메일). changed_by_type=OPERATOR일 때만 값 존재';
COMMENT ON COLUMN office_registration_status_history.reason IS '변경 사유(길이 제한 없는 자유 서술, 담당자 이름과는 분리)';
COMMENT ON COLUMN office_registration_status_history.created_at IS '상태 변경 일시';

CREATE TABLE document_move_outbox (
    id                      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    office_registration_id  BIGINT      NOT NULL REFERENCES office_registration(id) ON DELETE RESTRICT,
    task_type               VARCHAR(30) NOT NULL CHECK (task_type IN ('MOVE_TO_PENDING_DELETION')),
    status                  VARCHAR(20) NOT NULL DEFAULT 'PENDING' CHECK (status IN ('PENDING','IN_PROGRESS','DONE','FAILED')),
    attempt_count           INTEGER     NOT NULL DEFAULT 0,
    next_attempt_at         TIMESTAMPTZ NOT NULL DEFAULT now(),
    locked_at               TIMESTAMPTZ,
    locked_by               VARCHAR(100),
    lock_token              UUID,
    lock_expires_at         TIMESTAMPTZ,
    last_error              TEXT,
    created_at              TIMESTAMPTZ NOT NULL DEFAULT now(),
    processed_at            TIMESTAMPTZ
);

CREATE UNIQUE INDEX uq_document_move_outbox_active
    ON document_move_outbox (office_registration_id, task_type)
    WHERE status IN ('PENDING','IN_PROGRESS');

ALTER TABLE document_move_outbox ADD CONSTRAINT ck_outbox_status CHECK (
    (status = 'PENDING'
        AND locked_at IS NULL AND locked_by IS NULL AND lock_token IS NULL AND lock_expires_at IS NULL
        AND processed_at IS NULL)
    OR (status = 'IN_PROGRESS'
        AND locked_at IS NOT NULL AND locked_by IS NOT NULL AND lock_token IS NOT NULL AND lock_expires_at IS NOT NULL
        AND processed_at IS NULL)
    OR (status = 'DONE'
        AND processed_at IS NOT NULL
        AND locked_at IS NULL AND locked_by IS NULL AND lock_token IS NULL AND lock_expires_at IS NULL)
    OR (status = 'FAILED'
        AND last_error IS NOT NULL
        AND locked_at IS NULL AND locked_by IS NULL AND lock_token IS NULL AND lock_expires_at IS NULL)
);

CREATE INDEX ix_document_move_outbox_due ON document_move_outbox (next_attempt_at) WHERE status = 'PENDING';
CREATE INDEX ix_document_move_outbox_stuck ON document_move_outbox (lock_expires_at) WHERE status = 'IN_PROGRESS';

COMMENT ON TABLE document_move_outbox IS 'S3 증빙서류 이동(반려 시 verified→pending-deletion) 작업 큐(outbox 패턴)';
COMMENT ON COLUMN document_move_outbox.id IS '작업 내부 식별자';
COMMENT ON COLUMN document_move_outbox.office_registration_id IS '대상 신청';
COMMENT ON COLUMN document_move_outbox.task_type IS '작업 종류(현재는 MOVE_TO_PENDING_DELETION 하나)';
COMMENT ON COLUMN document_move_outbox.status IS '작업 상태: PENDING 대기, IN_PROGRESS 처리중, DONE 완료, FAILED 재시도 소진';
COMMENT ON COLUMN document_move_outbox.attempt_count IS '재시도 횟수(일반 카운터, 상한 없음)';
COMMENT ON COLUMN document_move_outbox.next_attempt_at IS '다음 재시도 예정 시각(지수 백오프)';
COMMENT ON COLUMN document_move_outbox.locked_at IS '워커가 lease를 획득한 시각';
COMMENT ON COLUMN document_move_outbox.locked_by IS 'lease를 획득한 워커 인스턴스 식별자';
COMMENT ON COLUMN document_move_outbox.lock_token IS 'lease 획득마다 새로 발급하는 fencing token — 뒤늦게 돌아온 워커의 덮어쓰기 방지';
COMMENT ON COLUMN document_move_outbox.lock_expires_at IS 'lease 만료 시각(만료되면 다른 워커가 회수 가능)';
COMMENT ON COLUMN document_move_outbox.last_error IS '가장 최근 실패 사유(길이 제한 없는 자유 서술)';
COMMENT ON COLUMN document_move_outbox.created_at IS '작업 적재 일시';
COMMENT ON COLUMN document_move_outbox.processed_at IS '작업 완료 일시';

CREATE TABLE office_membership (
    id                                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    member_id                        BIGINT      NOT NULL REFERENCES member(id) ON DELETE RESTRICT,
    office_id                        BIGINT      NOT NULL REFERENCES office(id) ON DELETE RESTRICT,
    role                              VARCHAR(10) NOT NULL CHECK (role IN ('ADMIN','STAFF')),
    status                            VARCHAR(10) NOT NULL DEFAULT 'PENDING' CHECK (status IN ('PENDING','APPROVED','REJECTED','REVOKED')),
    created_at                        TIMESTAMPTZ NOT NULL DEFAULT now(),
    reviewed_at                       TIMESTAMPTZ,
    reviewed_by_type                  VARCHAR(10) CHECK (reviewed_by_type IN ('ADMIN','OPERATOR','SYSTEM')),
    reviewed_by_membership_id         BIGINT,
    reviewed_by_operator_identifier   VARCHAR(100),
    rejection_reason                  TEXT,
    revoked_at                        TIMESTAMPTZ,
    revocation_reason                 TEXT,
    UNIQUE (member_id, office_id),
    UNIQUE (id, member_id, office_id),
    UNIQUE (id, office_id)
);

ALTER TABLE office_membership
    ADD CONSTRAINT fk_membership_reviewed_by
    FOREIGN KEY (reviewed_by_membership_id, office_id)
    REFERENCES office_membership (id, office_id)
    ON DELETE RESTRICT;

ALTER TABLE office_membership ADD CONSTRAINT ck_office_membership_reviewer CHECK (
    reviewed_by_type IS NULL
    OR (reviewed_by_type = 'ADMIN'
        AND reviewed_by_membership_id IS NOT NULL AND reviewed_by_operator_identifier IS NULL)
    OR (reviewed_by_type = 'OPERATOR'
        AND reviewed_by_membership_id IS NULL AND reviewed_by_operator_identifier IS NOT NULL)
    OR (reviewed_by_type = 'SYSTEM'
        AND reviewed_by_membership_id IS NULL AND reviewed_by_operator_identifier IS NULL)
);

ALTER TABLE office_membership ADD CONSTRAINT ck_office_membership_status CHECK (
    (status = 'PENDING'
        AND reviewed_at IS NULL AND reviewed_by_type IS NULL
        AND reviewed_by_membership_id IS NULL AND reviewed_by_operator_identifier IS NULL
        AND rejection_reason IS NULL AND revoked_at IS NULL AND revocation_reason IS NULL)
    OR (status = 'APPROVED'
        AND reviewed_at IS NOT NULL AND reviewed_by_type IS NOT NULL
        AND rejection_reason IS NULL AND revoked_at IS NULL AND revocation_reason IS NULL)
    OR (status = 'REJECTED'
        AND reviewed_at IS NOT NULL AND reviewed_by_type IS NOT NULL
        AND rejection_reason IS NOT NULL AND revoked_at IS NULL AND revocation_reason IS NULL)
    OR (status = 'REVOKED'
        AND reviewed_at IS NOT NULL AND reviewed_by_type IS NOT NULL
        AND rejection_reason IS NULL AND revoked_at IS NOT NULL AND revocation_reason IS NOT NULL)
);

CREATE INDEX ix_office_membership_member_status ON office_membership (member_id, status);

COMMENT ON TABLE office_membership IS '사무소 소속(회원↔사무소 관계, 관리자/직원 권한)';
COMMENT ON COLUMN office_membership.id IS '소속 내부 식별자';
COMMENT ON COLUMN office_membership.member_id IS '소속된 회원';
COMMENT ON COLUMN office_membership.office_id IS '소속된 사무소';
COMMENT ON COLUMN office_membership.role IS '역할: ADMIN 관리자, STAFF 일반직원';
COMMENT ON COLUMN office_membership.status IS '소속 상태: PENDING 승인대기, APPROVED 승인, REJECTED 거절, REVOKED 회수(탈퇴/해제)';
COMMENT ON COLUMN office_membership.created_at IS '최초 신청 일시';
COMMENT ON COLUMN office_membership.reviewed_at IS '승인·거절 처리 일시';
COMMENT ON COLUMN office_membership.reviewed_by_type IS '심사 주체: ADMIN 사무소 관리자, OPERATOR 사이로 운영자, SYSTEM 시스템(최초 ADMIN 생성 등)';
COMMENT ON COLUMN office_membership.reviewed_by_membership_id IS '심사한 관리자의 membership(reviewed_by_type=ADMIN일 때만)';
COMMENT ON COLUMN office_membership.reviewed_by_operator_identifier IS '심사한 운영자 식별자(reviewed_by_type=OPERATOR일 때만)';
COMMENT ON COLUMN office_membership.rejection_reason IS '거절 사유(길이 제한 없는 자유 서술)';
COMMENT ON COLUMN office_membership.revoked_at IS '권한 회수(REVOKED 전환) 일시';
COMMENT ON COLUMN office_membership.revocation_reason IS '권한 회수 사유(길이 제한 없는 자유 서술)';

CREATE TABLE office_membership_status_history (
    id                        BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    office_membership_id      BIGINT      NOT NULL,
    office_id                 BIGINT      NOT NULL,
    from_status               VARCHAR(10) CHECK (from_status IS NULL OR from_status IN ('PENDING','APPROVED','REJECTED','REVOKED')),
    to_status                 VARCHAR(10) NOT NULL CHECK (to_status IN ('PENDING','APPROVED','REJECTED','REVOKED')),
    changed_by_type           VARCHAR(10) NOT NULL CHECK (changed_by_type IN ('APPLICANT','ADMIN','SYSTEM')),
    changed_by_membership_id  BIGINT,
    reason                    TEXT,
    created_at                TIMESTAMPTZ NOT NULL DEFAULT now()
);

ALTER TABLE office_membership_status_history
    ADD CONSTRAINT fk_membership_history_parent
    FOREIGN KEY (office_membership_id, office_id)
    REFERENCES office_membership (id, office_id)
    ON DELETE RESTRICT;

ALTER TABLE office_membership_status_history
    ADD CONSTRAINT fk_membership_history_changed_by
    FOREIGN KEY (changed_by_membership_id, office_id)
    REFERENCES office_membership (id, office_id)
    ON DELETE RESTRICT;

ALTER TABLE office_membership_status_history ADD CONSTRAINT ck_membership_history_actor CHECK (
    (changed_by_type = 'ADMIN'
        AND changed_by_membership_id IS NOT NULL
        AND (
            changed_by_membership_id != office_membership_id
            OR (from_status = 'APPROVED' AND to_status = 'REVOKED')
        ))
    OR (changed_by_type IN ('APPLICANT','SYSTEM') AND changed_by_membership_id IS NULL)
);

COMMENT ON TABLE office_membership_status_history IS '사무소 소속 상태 변경 이력';
COMMENT ON COLUMN office_membership_status_history.id IS '이력 내부 식별자';
COMMENT ON COLUMN office_membership_status_history.office_membership_id IS '대상 소속';
COMMENT ON COLUMN office_membership_status_history.office_id IS '비정규화된 사무소 ID(복합 FK로 부모와 일치 검증됨)';
COMMENT ON COLUMN office_membership_status_history.from_status IS '변경 전 상태(최초 생성 시 NULL)';
COMMENT ON COLUMN office_membership_status_history.to_status IS '변경 후 상태';
COMMENT ON COLUMN office_membership_status_history.changed_by_type IS '변경 주체: APPLICANT 신청자 본인, ADMIN 사무소 관리자, SYSTEM 시스템';
COMMENT ON COLUMN office_membership_status_history.changed_by_membership_id IS '변경을 실행한 관리자의 membership(changed_by_type=ADMIN일 때만). 자기참조는 자진 탈퇴(APPROVED→REVOKED)에서만 허용';
COMMENT ON COLUMN office_membership_status_history.reason IS '변경 사유(길이 제한 없는 자유 서술)';
COMMENT ON COLUMN office_membership_status_history.created_at IS '상태 변경 일시';
