-- 매물, 임장 조율, 후보시간, 상태 이력

CREATE TABLE property (
    id                       BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    office_id                BIGINT       NOT NULL REFERENCES office(id) ON DELETE RESTRICT,
    name                     VARCHAR(50),
    address_base             VARCHAR(200) NOT NULL,
    address_detail           VARCHAR(100),
    deal_type                VARCHAR(10)  NOT NULL CHECK (deal_type IN ('SALE','JEONSE','MONTHLY')),
    has_contract             BOOLEAN      NOT NULL,
    contract_expiry_date     DATE,
    property_status          VARCHAR(15)  NOT NULL CHECK (property_status IN ('ACTIVE','NO_CONTRACT','NEGOTIATING')),
    landlord_name            VARCHAR(50),
    landlord_phone           VARCHAR(20),
    current_occupant_name    VARCHAR(50),
    current_occupant_phone   VARCHAR(20),
    created_at               TIMESTAMPTZ  NOT NULL DEFAULT now(),
    updated_at               TIMESTAMPTZ  NOT NULL,
    deleted_at               TIMESTAMPTZ,
    deleted_by_member_id     BIGINT,
    UNIQUE (id, office_id)
);

ALTER TABLE property
    ADD CONSTRAINT fk_property_deleted_by_membership
    FOREIGN KEY (deleted_by_member_id, office_id)
    REFERENCES office_membership (member_id, office_id)
    ON DELETE RESTRICT;

ALTER TABLE property ADD CONSTRAINT ck_property_deal_state CHECK (
    (has_contract = false AND property_status = 'NO_CONTRACT' AND contract_expiry_date IS NULL)
    OR
    (has_contract = true AND property_status IN ('ACTIVE','NEGOTIATING') AND contract_expiry_date IS NOT NULL)
);

ALTER TABLE property ADD CONSTRAINT ck_property_soft_delete CHECK (
    (deleted_at IS NULL AND deleted_by_member_id IS NULL)
    OR (deleted_at IS NOT NULL AND deleted_by_member_id IS NOT NULL)
);

CREATE INDEX ix_property_active ON property (office_id, property_status) WHERE deleted_at IS NULL;

COMMENT ON TABLE property IS '매물';
COMMENT ON COLUMN property.id IS '매물 내부 식별자';
COMMENT ON COLUMN property.office_id IS '매물을 보유한 사무소';
COMMENT ON COLUMN property.name IS '매물 별칭(선택)';
COMMENT ON COLUMN property.address_base IS '매물 기본 주소';
COMMENT ON COLUMN property.address_detail IS '매물 상세 주소';
COMMENT ON COLUMN property.deal_type IS '거래 유형: SALE 매매, JEONSE 전세, MONTHLY 월세';
COMMENT ON COLUMN property.has_contract IS '현재 계약 존재 여부';
COMMENT ON COLUMN property.contract_expiry_date IS '계약 만기일(계약이 있을 때만)';
COMMENT ON COLUMN property.property_status IS '매물 상태: ACTIVE 계약중, NO_CONTRACT 계약없음, NEGOTIATING 협의중';
COMMENT ON COLUMN property.landlord_name IS '임대인 이름';
COMMENT ON COLUMN property.landlord_phone IS '임대인 연락처';
COMMENT ON COLUMN property.current_occupant_name IS '현재 거주자 이름';
COMMENT ON COLUMN property.current_occupant_phone IS '현재 거주자 연락처';
COMMENT ON COLUMN property.created_at IS '매물 등록 일시';
COMMENT ON COLUMN property.updated_at IS '마지막 수정 일시(애플리케이션 또는 트리거가 갱신 — DEFAULT로는 UPDATE 시 자동 갱신 안 됨)';
COMMENT ON COLUMN property.deleted_at IS '소프트 삭제 일시';
COMMENT ON COLUMN property.deleted_by_member_id IS '소프트 삭제를 실행한 회원(해당 사무소 소속만 가능, 복합 FK로 검증)';

CREATE TABLE coordination (
    id                           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    office_id                    BIGINT       NOT NULL,
    property_id                  BIGINT       NOT NULL,
    created_by_member_id         BIGINT       NOT NULL,
    customer_name                VARCHAR(20)  NOT NULL,
    customer_phone               VARCHAR(20)  NOT NULL,
    status                       VARCHAR(20)  NOT NULL DEFAULT 'PENDING_RESPONSE'
                                  CHECK (status IN ('PENDING_RESPONSE','RESPONDED','CONFIRMED','COMPLETED','CANCELLED','NEEDS_REBOOKING')),
    link_token_hash              VARCHAR(64)  NOT NULL UNIQUE,
    link_expires_at              TIMESTAMPTZ  NOT NULL,
    link_revoked_at              TIMESTAMPTZ,
    confirmed_candidate_time_id  BIGINT,
    origin_coordination_id       BIGINT       REFERENCES coordination(id) ON DELETE RESTRICT,
    rebooking_requested_at       TIMESTAMPTZ,
    created_at                   TIMESTAMPTZ  NOT NULL DEFAULT now(),
    last_responded_at            TIMESTAMPTZ,
    confirmed_at                 TIMESTAMPTZ,
    completed_at                 TIMESTAMPTZ,
    cancelled_at                 TIMESTAMPTZ,
    UNIQUE (id, office_id)
);

ALTER TABLE coordination
    ADD CONSTRAINT fk_coordination_property_office
    FOREIGN KEY (property_id, office_id) REFERENCES property (id, office_id)
    ON DELETE RESTRICT;

ALTER TABLE coordination
    ADD CONSTRAINT fk_coordination_created_by_membership
    FOREIGN KEY (created_by_member_id, office_id) REFERENCES office_membership (member_id, office_id)
    ON DELETE RESTRICT;

CREATE TABLE coordination_candidate_time (
    id                        BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    coordination_id           BIGINT  NOT NULL REFERENCES coordination(id) ON DELETE CASCADE,
    candidate_date            DATE    NOT NULL,
    start_time                TIME    NOT NULL,
    is_selected_by_customer   BOOLEAN NOT NULL DEFAULT false,
    UNIQUE (id, coordination_id),
    UNIQUE (coordination_id, candidate_date, start_time)
);

CREATE INDEX ix_candidate_time_coordination_date ON coordination_candidate_time (coordination_id, candidate_date, start_time);

-- coordination_candidate_time이 생긴 뒤에야 걸 수 있는 순환 FK
ALTER TABLE coordination
    ADD CONSTRAINT fk_coordination_confirmed_time
    FOREIGN KEY (confirmed_candidate_time_id, id)
    REFERENCES coordination_candidate_time (id, coordination_id)
    ON DELETE RESTRICT;

ALTER TABLE coordination ADD CONSTRAINT ck_coordination_confirmation_pair CHECK (
    (confirmed_candidate_time_id IS NULL) = (confirmed_at IS NULL)
);

ALTER TABLE coordination ADD CONSTRAINT ck_coordination_status_columns CHECK (
    (status = 'PENDING_RESPONSE'
        AND last_responded_at IS NULL AND confirmed_at IS NULL
        AND completed_at IS NULL AND cancelled_at IS NULL AND rebooking_requested_at IS NULL)
    OR (status = 'RESPONDED'
        AND last_responded_at IS NOT NULL AND confirmed_at IS NULL
        AND completed_at IS NULL AND cancelled_at IS NULL AND rebooking_requested_at IS NULL)
    OR (status = 'CONFIRMED'
        AND confirmed_at IS NOT NULL
        AND completed_at IS NULL AND cancelled_at IS NULL AND rebooking_requested_at IS NULL)
    OR (status = 'COMPLETED'
        AND confirmed_at IS NOT NULL AND completed_at IS NOT NULL
        AND cancelled_at IS NULL AND rebooking_requested_at IS NULL)
    OR (status = 'CANCELLED'
        AND cancelled_at IS NOT NULL
        AND completed_at IS NULL AND rebooking_requested_at IS NULL)
    OR (status = 'NEEDS_REBOOKING'
        AND rebooking_requested_at IS NOT NULL AND confirmed_at IS NULL
        AND completed_at IS NULL AND cancelled_at IS NULL)
);

CREATE UNIQUE INDEX uq_coordination_origin
    ON coordination (origin_coordination_id)
    WHERE origin_coordination_id IS NOT NULL;

CREATE INDEX ix_coordination_office_status_created ON coordination (office_id, status, created_at);
CREATE INDEX ix_coordination_office_confirmed ON coordination (office_id, confirmed_at);

COMMENT ON TABLE coordination IS '임장(현장방문) 조율';
COMMENT ON COLUMN coordination.id IS '조율 내부 식별자';
COMMENT ON COLUMN coordination.office_id IS '이 조율을 관리하는 사무소';
COMMENT ON COLUMN coordination.property_id IS '조율 대상 매물';
COMMENT ON COLUMN coordination.created_by_member_id IS '조율을 생성한 사무소 회원';
COMMENT ON COLUMN coordination.customer_name IS '고객(비회원) 이름';
COMMENT ON COLUMN coordination.customer_phone IS '고객(비회원) 연락처';
COMMENT ON COLUMN coordination.status IS '조율 상태: PENDING_RESPONSE 응답대기, RESPONDED 응답완료, CONFIRMED 일정확정, COMPLETED 임장완료, CANCELLED 취소, NEEDS_REBOOKING 재응답필요(terminal)';
COMMENT ON COLUMN coordination.link_token_hash IS '고객 공개 링크 토큰의 해시값';
COMMENT ON COLUMN coordination.link_expires_at IS '공개 링크 만료 시각';
COMMENT ON COLUMN coordination.link_revoked_at IS '공개 링크 강제 폐기 시각';
COMMENT ON COLUMN coordination.confirmed_candidate_time_id IS '확정된 후보시간(고객이 선택하고 사무소가 확정한 것)';
COMMENT ON COLUMN coordination.origin_coordination_id IS '재응답필요 후 새로 생성된 경우, 원본 조율(1:1)';
COMMENT ON COLUMN coordination.rebooking_requested_at IS '재응답필요 진입 시각';
COMMENT ON COLUMN coordination.created_at IS '조율 생성 일시';
COMMENT ON COLUMN coordination.last_responded_at IS '고객의 마지막 응답 시각';
COMMENT ON COLUMN coordination.confirmed_at IS '일정 확정 시각';
COMMENT ON COLUMN coordination.completed_at IS '임장 완료 처리 시각';
COMMENT ON COLUMN coordination.cancelled_at IS '취소 처리 시각';

COMMENT ON TABLE coordination_candidate_time IS '조율 후보시간';
COMMENT ON COLUMN coordination_candidate_time.id IS '후보시간 내부 식별자';
COMMENT ON COLUMN coordination_candidate_time.coordination_id IS '소속된 조율';
COMMENT ON COLUMN coordination_candidate_time.candidate_date IS '후보 날짜';
COMMENT ON COLUMN coordination_candidate_time.start_time IS '후보 시작 시각(국내 단일 시간대 기준 TIME)';
COMMENT ON COLUMN coordination_candidate_time.is_selected_by_customer IS '고객이 이 후보시간을 선택했는지 여부';

CREATE TABLE coordination_status_history (
    id                     BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    coordination_id        BIGINT      NOT NULL,
    office_id               BIGINT      NOT NULL,
    from_status              VARCHAR(20) CHECK (from_status IS NULL OR from_status IN ('PENDING_RESPONSE','RESPONDED','CONFIRMED','COMPLETED','CANCELLED','NEEDS_REBOOKING')),
    to_status                VARCHAR(20) NOT NULL CHECK (to_status IN ('PENDING_RESPONSE','RESPONDED','CONFIRMED','COMPLETED','CANCELLED','NEEDS_REBOOKING')),
    changed_by_member_id     BIGINT,
    change_source            VARCHAR(20) NOT NULL CHECK (change_source IN ('OFFICE_MEMBER','CUSTOMER_LINK','SYSTEM_BATCH')),
    reason                   TEXT,
    created_at               TIMESTAMPTZ NOT NULL DEFAULT now()
);

ALTER TABLE coordination_status_history
    ADD CONSTRAINT fk_status_history_parent
    FOREIGN KEY (coordination_id, office_id)
    REFERENCES coordination (id, office_id)
    ON DELETE RESTRICT;

ALTER TABLE coordination_status_history
    ADD CONSTRAINT fk_status_history_changed_by_membership
    FOREIGN KEY (changed_by_member_id, office_id) REFERENCES office_membership (member_id, office_id)
    ON DELETE RESTRICT;

ALTER TABLE coordination_status_history ADD CONSTRAINT ck_status_history_actor CHECK (
    (change_source = 'OFFICE_MEMBER' AND changed_by_member_id IS NOT NULL)
    OR (change_source IN ('CUSTOMER_LINK','SYSTEM_BATCH') AND changed_by_member_id IS NULL)
);

CREATE INDEX ix_status_history_coordination_created ON coordination_status_history (coordination_id, created_at);

COMMENT ON TABLE coordination_status_history IS '조율 상태 변경 이력';
COMMENT ON COLUMN coordination_status_history.id IS '이력 내부 식별자';
COMMENT ON COLUMN coordination_status_history.coordination_id IS '대상 조율';
COMMENT ON COLUMN coordination_status_history.office_id IS '비정규화된 사무소 ID(복합 FK로 부모와 일치 검증됨)';
COMMENT ON COLUMN coordination_status_history.from_status IS '변경 전 상태(최초 생성 시 NULL)';
COMMENT ON COLUMN coordination_status_history.to_status IS '변경 후 상태';
COMMENT ON COLUMN coordination_status_history.changed_by_member_id IS '변경을 실행한 사무소 회원(고객이 바꾼 경우 NULL)';
COMMENT ON COLUMN coordination_status_history.change_source IS '변경 출처: OFFICE_MEMBER 사무소 회원, CUSTOMER_LINK 고객 공개링크, SYSTEM_BATCH 시스템 배치';
COMMENT ON COLUMN coordination_status_history.reason IS '변경 사유(길이 제한 없는 자유 서술)';
COMMENT ON COLUMN coordination_status_history.created_at IS '상태 변경 일시';
