-- D-90 계약 만기 업무, ShedLock(D-90 배치 분산 락)
-- shedlock은 net.javacrumbs.shedlock 라이브러리 표준 스키마 그대로 따름

CREATE TABLE expiry_task (
    id                     BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    office_id               BIGINT      NOT NULL,
    property_id             BIGINT      NOT NULL,
    task_type               VARCHAR(10) NOT NULL DEFAULT 'D90',
    contract_expiry_date    DATE        NOT NULL,
    target_date             DATE        NOT NULL,
    status                  VARCHAR(10) NOT NULL DEFAULT 'OPEN' CHECK (status IN ('OPEN','COMPLETED','CANCELLED')),
    created_at              TIMESTAMPTZ NOT NULL DEFAULT now(),
    completed_at            TIMESTAMPTZ,
    cancelled_at            TIMESTAMPTZ,
    cancel_reason           VARCHAR(30) CHECK (cancel_reason IS NULL OR cancel_reason IN ('PROPERTY_SOFT_DELETED','CONTRACT_ENDED')),
    UNIQUE (property_id, task_type, contract_expiry_date)
);

ALTER TABLE expiry_task
    ADD CONSTRAINT fk_expiry_task_property_office
    FOREIGN KEY (property_id, office_id) REFERENCES property (id, office_id)
    ON DELETE RESTRICT;

ALTER TABLE expiry_task
    ADD CONSTRAINT ck_expiry_task_target_date
    CHECK (target_date = contract_expiry_date - 90);

ALTER TABLE expiry_task ADD CONSTRAINT ck_expiry_task_type CHECK (task_type = 'D90');

ALTER TABLE expiry_task ADD CONSTRAINT ck_expiry_task_status CHECK (
    (status = 'OPEN' AND completed_at IS NULL AND cancelled_at IS NULL AND cancel_reason IS NULL)
    OR (status = 'COMPLETED' AND completed_at IS NOT NULL AND cancelled_at IS NULL AND cancel_reason IS NULL)
    OR (status = 'CANCELLED' AND completed_at IS NULL AND cancelled_at IS NOT NULL AND cancel_reason IS NOT NULL)
);

CREATE UNIQUE INDEX uq_expiry_task_open ON expiry_task (property_id, task_type) WHERE status = 'OPEN';
CREATE INDEX ix_expiry_task_office_status_target ON expiry_task (office_id, status, target_date);

COMMENT ON TABLE expiry_task IS 'D-90 계약 만기 업무';
COMMENT ON COLUMN expiry_task.id IS '업무 내부 식별자';
COMMENT ON COLUMN expiry_task.office_id IS '업무를 관리하는 사무소';
COMMENT ON COLUMN expiry_task.property_id IS '대상 매물';
COMMENT ON COLUMN expiry_task.task_type IS '업무 종류(현재는 D90 하나로 고정)';
COMMENT ON COLUMN expiry_task.contract_expiry_date IS '계약 만기일';
COMMENT ON COLUMN expiry_task.target_date IS '업무 처리 목표일(만기일 - 90일)';
COMMENT ON COLUMN expiry_task.status IS '업무 상태: OPEN 진행중, COMPLETED 완료, CANCELLED 취소';
COMMENT ON COLUMN expiry_task.created_at IS '업무 생성 일시(D-90 배치가 생성)';
COMMENT ON COLUMN expiry_task.completed_at IS '업무 완료 처리 일시';
COMMENT ON COLUMN expiry_task.cancelled_at IS '업무 취소 처리 일시';
COMMENT ON COLUMN expiry_task.cancel_reason IS '취소 사유: PROPERTY_SOFT_DELETED 매물 소프트삭제, CONTRACT_ENDED 계약 해소';

CREATE TABLE shedlock (
    name        VARCHAR(64)  NOT NULL PRIMARY KEY,
    lock_until  TIMESTAMP(3) NOT NULL,
    locked_at   TIMESTAMP(3) NOT NULL,
    locked_by   VARCHAR(255) NOT NULL
);

COMMENT ON TABLE shedlock IS 'D-90 배치 분산 락(ShedLock 라이브러리 표준 스키마)';
COMMENT ON COLUMN shedlock.name IS '락 이름(배치 작업 식별자)';
COMMENT ON COLUMN shedlock.lock_until IS '락 만료 시각';
COMMENT ON COLUMN shedlock.locked_at IS '락 획득 시각';
COMMENT ON COLUMN shedlock.locked_by IS '락을 획득한 인스턴스 식별자';
