-- 약관 동의 이력, 카카오 OAuth 왕복 상태, 이메일 인증코드 소비 기록, 요청 제한 카운터, 사무소 단일 소속 제약 추가

CREATE TABLE terms_catalog (
    terms_code    VARCHAR(30)  NOT NULL,
    terms_version VARCHAR(20)  NOT NULL,
    required      BOOLEAN      NOT NULL,
    withdrawable  BOOLEAN      NOT NULL,
    effective_at  TIMESTAMPTZ  NOT NULL,
    content_hash  VARCHAR(64)  NOT NULL,
    created_at    TIMESTAMPTZ  NOT NULL DEFAULT now(),
    PRIMARY KEY (terms_code, terms_version)
);

ALTER TABLE terms_catalog ADD CONSTRAINT ck_terms_catalog_version_format
    CHECK (terms_version ~ '^[0-9]{4}-(0[1-9]|1[0-2])-(0[1-9]|[12][0-9]|3[01])$');

COMMENT ON TABLE terms_catalog IS '약관·개인정보처리방침 버전 카탈로그. 실제 서비스에 노출되는 버전은 여기 등록된 것만이며, terms_version은 실제 시행일(YYYY-MM-DD) 형식으로만 등록한다. draft 접두사의 검토용 초안은 CHECK 제약으로 등록을 차단한다. 정확한 약관 목록·조문·필수 여부·시행일은 파일럿 전 법률 검토 후 행으로 확정한다';
COMMENT ON COLUMN terms_catalog.terms_code IS '약관 종류 코드. 실제 코드 목록과 필수·선택 구분은 파일럿 전 법률 검토로 확정하며, 별도 동의가 필요한 항목은 각각 다른 코드로 관리한다';
COMMENT ON COLUMN terms_catalog.terms_version IS '시행일 기준 버전(YYYY-MM-DD). 검토 중인 초안은 운영 카탈로그에 등록하지 않으며 가입·동의 API는 카탈로그에 있는 버전만 유효하게 인정한다';
COMMENT ON COLUMN terms_catalog.required IS '신규가입 시 agreed=true가 아니면 가입 자체를 거부하는 필수 약관인지';
COMMENT ON COLUMN terms_catalog.withdrawable IS '가입 후 별도로 동의를 철회할 수 있는지(예: 마케팅 수신동의는 true, 이용약관은 철회하면 탈퇴와 동치이므로 false)';
COMMENT ON COLUMN terms_catalog.effective_at IS '이 버전이 실제로 유효해지는 시각. 서버는 이 시각 이후의 신규 동의 요청에만 이 버전을 유효 버전으로 취급한다';
COMMENT ON COLUMN terms_catalog.content_hash IS '약관 본문의 해시(SHA-256 등). 나중에 "그때 실제로 무슨 문구에 동의했는지" 본문 원문과 대조 검증할 때 쓴다 — 본문 자체는 이 DB가 아니라 별도 정적 자산(프론트 배포물 등)으로 관리';
COMMENT ON COLUMN terms_catalog.created_at IS '이 카탈로그 행이 등록된 시각(시행 시각과 다를 수 있음 — 시행 전에 미리 등록 가능)';

CREATE TABLE terms_agreement (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    member_id      BIGINT       NOT NULL REFERENCES member(id) ON DELETE RESTRICT,
    terms_code     VARCHAR(30)  NOT NULL,
    terms_version  VARCHAR(20)  NOT NULL,
    agreed         BOOLEAN      NOT NULL,
    recorded_at    TIMESTAMPTZ  NOT NULL DEFAULT now()
);

ALTER TABLE terms_agreement
    ADD CONSTRAINT fk_terms_agreement_catalog
    FOREIGN KEY (terms_code, terms_version) REFERENCES terms_catalog (terms_code, terms_version)
    ON DELETE RESTRICT;

CREATE INDEX ix_terms_agreement_member_code
    ON terms_agreement (member_id, terms_code, recorded_at DESC, id DESC);

COMMENT ON TABLE terms_agreement IS '약관·개인정보 동의/철회 이벤트 로그(감사 목적, append-only, UPDATE·DELETE 없음). 회원의 현재 동의 상태는 (member_id, terms_code)별 최신 행(ORDER BY recorded_at DESC, id DESC LIMIT 1)의 agreed 값으로 판단한다. id는 동일 recorded_at에 두 이벤트가 기록될 때 순서를 결정하는 보조 정렬 기준이다. 철회는 기존 행 수정 없이 agreed=false인 새 행으로 기록한다. terms_code+terms_version은 terms_catalog에 등록된 조합만 참조할 수 있다. 애플리케이션 DB 역할에서 이 테이블의 UPDATE·DELETE 권한을 회수해 append-only를 권한으로도 강제한다';
COMMENT ON COLUMN terms_agreement.id IS '이벤트 내부 식별자';
COMMENT ON COLUMN terms_agreement.member_id IS '이벤트의 대상 회원';
COMMENT ON COLUMN terms_agreement.terms_code IS '약관 종류. terms_catalog 참고';
COMMENT ON COLUMN terms_agreement.terms_version IS '이 이벤트 시점에 유효했던 약관 버전(terms_catalog.terms_version 참조). 서버가 현재 유효 버전과 대조해 검증';
COMMENT ON COLUMN terms_agreement.agreed IS '이 이벤트가 동의인지 철회인지. true=동의, false=철회. 필수 약관(terms_catalog.required=true)은 신규가입 시 true가 아니면 가입 자체가 거부됨(서비스 계층 검증)';
COMMENT ON COLUMN terms_agreement.recorded_at IS '이 이벤트가 기록된 일시 — 서버 시각으로만 기록, 클라이언트가 보낸 값이 아님. 행 자체를 절대 수정하지 않으므로 별도 created_at 컬럼을 두지 않음';

CREATE TABLE oauth_transaction (
    id                     BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    state_hash             VARCHAR(64)  NOT NULL UNIQUE,
    purpose                VARCHAR(10)  NOT NULL CHECK (purpose IN ('LOGIN','LINK')),
    member_id              BIGINT       REFERENCES member(id) ON DELETE RESTRICT,
    initiating_session_id  VARCHAR(100),
    step_up_verified_at    TIMESTAMPTZ,
    redirect_after         VARCHAR(200),
    expires_at             TIMESTAMPTZ  NOT NULL,
    used_at                TIMESTAMPTZ,
    created_at             TIMESTAMPTZ  NOT NULL DEFAULT now()
);

ALTER TABLE oauth_transaction ADD CONSTRAINT ck_oauth_transaction_purpose_fields
    CHECK (
        (purpose = 'LINK' AND member_id IS NOT NULL AND initiating_session_id IS NOT NULL AND step_up_verified_at IS NOT NULL)
        OR
        (purpose = 'LOGIN' AND member_id IS NULL AND initiating_session_id IS NULL AND step_up_verified_at IS NULL)
    );

ALTER TABLE oauth_transaction ADD CONSTRAINT ck_oauth_transaction_expires
    CHECK (expires_at > created_at);

ALTER TABLE oauth_transaction ADD CONSTRAINT ck_oauth_transaction_used
    CHECK (used_at IS NULL OR used_at >= created_at);

CREATE INDEX ix_oauth_transaction_expires ON oauth_transaction (expires_at) WHERE used_at IS NULL;

COMMENT ON TABLE oauth_transaction IS '카카오 OAuth 인가~콜백 왕복 상태. state는 순수 난수이고 의미는 이 테이블에만 있다(LOGIN/LINK 구분, LINK 대상 회원 등)';
COMMENT ON COLUMN oauth_transaction.id IS '트랜잭션 내부 식별자';
COMMENT ON COLUMN oauth_transaction.state_hash IS 'state 원문의 해시. 원문은 저장하지 않음(공개 링크 토큰과 동일한 원칙)';
COMMENT ON COLUMN oauth_transaction.purpose IS '목적: LOGIN 로그인/가입, LINK 기존 회원의 카카오 계정 연결';
COMMENT ON COLUMN oauth_transaction.member_id IS 'LINK일 때 연결 대상 회원. LOGIN이면 NULL(체크 제약으로 강제)';
COMMENT ON COLUMN oauth_transaction.initiating_session_id IS 'LINK일 때 authorize 호출 시점의 세션 식별자, 콜백 시점 세션과 일치해야 진행. LOGIN이면 NULL(체크 제약으로 강제)';
COMMENT ON COLUMN oauth_transaction.step_up_verified_at IS 'LINK일 때 authorize 호출 직전에 확인된 step-up 인증 시각, 콜백에서 이 값의 신선도를 재검증. LOGIN이면 NULL(체크 제약으로 강제)';
COMMENT ON COLUMN oauth_transaction.redirect_after IS '콜백 처리 후 리다이렉트할 프론트엔드 경로. 임의 URL이 아니라 서버 allowlist로만 제한';
COMMENT ON COLUMN oauth_transaction.expires_at IS '만료 시각(발급 후 10분)';
COMMENT ON COLUMN oauth_transaction.used_at IS '콜백에서 성공·실패와 무관하게 소비 처리된 시각. 이후 같은 state 재사용 불가';
COMMENT ON COLUMN oauth_transaction.created_at IS '발급 일시';

CREATE TABLE kakao_signup_ticket (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    provider_key  VARCHAR(255) NOT NULL,
    ticket_hash   VARCHAR(64)  NOT NULL UNIQUE,
    expires_at    TIMESTAMPTZ  NOT NULL,
    used_at       TIMESTAMPTZ,
    created_at    TIMESTAMPTZ  NOT NULL DEFAULT now()
);

ALTER TABLE kakao_signup_ticket ADD CONSTRAINT ck_kakao_signup_ticket_expires
    CHECK (expires_at > created_at);

ALTER TABLE kakao_signup_ticket ADD CONSTRAINT ck_kakao_signup_ticket_used
    CHECK (used_at IS NULL OR used_at >= created_at);

CREATE INDEX ix_kakao_signup_ticket_provider_key ON kakao_signup_ticket (provider_key);

COMMENT ON TABLE kakao_signup_ticket IS '카카오 신규가입 완료용 1회성 티켓. 콜백이 발급하고 가입완료 API가 소비한다(이메일 흐름의 challenge_id와 같은 역할)';
COMMENT ON COLUMN kakao_signup_ticket.id IS '티켓 내부 식별자';
COMMENT ON COLUMN kakao_signup_ticket.provider_key IS '카카오 고유 회원번호. 가입완료 시점에 이미 login_identity에 존재하면 409 처리';
COMMENT ON COLUMN kakao_signup_ticket.ticket_hash IS '티켓 원문의 해시. 원문은 HttpOnly+Secure 쿠키로만 전달하고 DB에는 저장하지 않음';
COMMENT ON COLUMN kakao_signup_ticket.expires_at IS '만료 시각(발급 후 10분)';
COMMENT ON COLUMN kakao_signup_ticket.used_at IS '가입 완료 처리로 소비된 시각. 이후 재사용 불가';
COMMENT ON COLUMN kakao_signup_ticket.created_at IS '발급 일시(카카오 콜백 처리 시점)';

CREATE TABLE rate_limit_counter (
    bucket_key         TEXT         PRIMARY KEY,
    window_started_at  TIMESTAMPTZ  NOT NULL,
    request_count      INT          NOT NULL DEFAULT 1
);

ALTER TABLE rate_limit_counter ADD CONSTRAINT ck_rate_limit_counter_count
    CHECK (request_count > 0);

CREATE INDEX ix_rate_limit_counter_window_started_at ON rate_limit_counter (window_started_at);

COMMENT ON TABLE rate_limit_counter IS '고정 윈도우 요청 제한 카운터. Redis 없이 PostgreSQL 원자적 UPSERT(INSERT ... ON CONFLICT (bucket_key) DO UPDATE ... RETURNING)로 갱신한다. bucket_key가 대상·액션·용도를 모두 인코딩하므로 별도 FK가 없다';
COMMENT ON COLUMN rate_limit_counter.bucket_key IS '제한 대상 키. 예: member:{memberId}:coordination-create, office:{officeId}:coordination-action-total, coordination:{coordinationId}:link-reissue, email-verification:send:{HMAC}, email-verification:verify:ip:{HMAC}. 이메일·IP는 인증코드 pepper와 분리된 요청 제한 전용 HMAC 키로 해시한 값만 저장한다';
COMMENT ON COLUMN rate_limit_counter.window_started_at IS '현재 윈도우 시작 시각. 매 요청마다 now()와 비교해 윈도우가 지났으면 이 값과 request_count를 함께 리셋한다. 요청이 없으면 갱신되지 않으며 정리 배치가 이 컬럼의 인덱스를 사용해 24시간 지난 행을 삭제한다';
COMMENT ON COLUMN rate_limit_counter.request_count IS '현재 윈도우 안의 요청 수. 윈도우 안에서는 원자적 UPSERT로 +1, 윈도우가 지나면 1로 리셋. 요청이 실제로 상태를 바꿨는지와 무관하게 매 호출마다 증가한다(재시도 자체도 부하이므로)';

ALTER TABLE email_verification_code ADD COLUMN consumed_at TIMESTAMPTZ;

ALTER TABLE email_verification_code ADD CONSTRAINT ck_email_verification_consumed
    CHECK (consumed_at IS NULL OR (status = 'VERIFIED' AND purpose IN ('SIGNUP','LOGIN')));

COMMENT ON COLUMN email_verification_code.consumed_at IS 'purpose=SIGNUP/LOGIN에서 이 challenge로 회원가입·로그인을 실제로 완료 처리한 시각. status=VERIFIED에서만 값을 가질 수 있고, 애플리케이션은 UPDATE ... WHERE challenge_id=? AND purpose=? AND status=''VERIFIED'' AND consumed_at IS NULL AND expires_at>now() RETURNING target_email 형태의 조건부 갱신으로 이 컬럼을 채워 동시 재사용·재생 공격을 막는다(영향행 0개면 이미 소비됨·만료됨·인증 미완료 중 하나). purpose를 WHERE에 반드시 포함해 다른 목적(STEP_UP 등)으로 발급된 challenge가 가입·로그인에 잘못 쓰이지 않게 하고, 로그인 대상 계정은 클라이언트가 보낸 이메일이 아니라 이 RETURNING target_email로만 결정한다';

CREATE UNIQUE INDEX uq_office_membership_member_approved
    ON office_membership (member_id)
    WHERE status = 'APPROVED';

COMMENT ON INDEX uq_office_membership_member_approved IS '공인중개사법 제12조의 이중등록 금지 원칙에 따라 회원당 APPROVED 사무소 소속을 최대 1개로 제한';
COMMENT ON TABLE office_membership IS '사무소 소속(회원↔사무소 관계, 관리자/직원 권한). 공인중개사법 제12조에 따라 회원당 APPROVED 소속은 최대 1개';

-- V2~V5 적용 이후 참조 DDL에서 문구가 다듬어진 기존 컬럼 COMMENT를 최종본과 동기화(구조 변경 없음)

COMMENT ON COLUMN coordination.origin_coordination_id IS '재응답 필요 후 새로 생성된 경우의 원본 조율. office_id와 함께 같은 사무소만 참조하며 자기참조는 금지';
COMMENT ON COLUMN coordination.rebooking_requested_at IS '재응답 필요 진입 시각';
COMMENT ON COLUMN coordination.status IS '조율 상태: PENDING_RESPONSE 응답 대기, RESPONDED 응답 완료, CONFIRMED 일정 확정, COMPLETED 임장 완료, CANCELLED 취소, NEEDS_REBOOKING 재응답 필요(terminal)';
COMMENT ON COLUMN coordination_status_history.office_id IS '사무소 ID';
COMMENT ON COLUMN document_move_outbox.status IS '작업 상태: PENDING 대기, IN_PROGRESS 처리 중, DONE 완료, FAILED 재시도 소진';
COMMENT ON COLUMN email_verification_code.status IS '코드 상태: ACTIVE 활성, VERIFIED 인증 완료, REPLACED 재발급으로 무효화, LOCKED 5회 실패로 잠김, EXPIRED 만료';
COMMENT ON COLUMN expiry_task.cancel_reason IS '취소 사유: PROPERTY_SOFT_DELETED 매물 삭제, CONTRACT_ENDED 계약 해소';
COMMENT ON COLUMN expiry_task.office_id IS '사무소 ID(매물 ID와 함께 복합 외래 키)';
COMMENT ON COLUMN expiry_task.property_id IS '매물 ID(사무소 ID와 함께 복합 외래 키)';
COMMENT ON COLUMN expiry_task.status IS '업무 상태: OPEN 진행 중, COMPLETED 완료, CANCELLED 취소';
COMMENT ON COLUMN login_history.login_identity_id IS '사용된 로그인 수단. member_id와 함께 해당 로그인 수단의 소유 회원을 복합 외래 키로 검증';
COMMENT ON COLUMN login_identity.revoked_at IS '연결 해제 일시';
COMMENT ON COLUMN office_membership_status_history.office_id IS '사무소 ID';
COMMENT ON COLUMN office_registration.status IS '심사 상태: PENDING_VERIFICATION 자동 검증 중, MANUAL_REVIEW 수동 심사 중, APPROVED 승인, REJECTED 반려';
COMMENT ON COLUMN property.deleted_at IS '삭제 일시';
COMMENT ON COLUMN property.deleted_by_member_id IS '삭제한 회원';
COMMENT ON COLUMN property.property_status IS '매물 상태: ACTIVE 계약 중, NO_CONTRACT 계약 없음, NEGOTIATING 협의 중. NEGOTIATING은 사용자 API 호출로 설정하지 않으며 D-90 일일 배치가 ACTIVE이고 OPEN expiry_task의 contract_expiry_date가 오늘보다 과거인 매물을 전환한다. 재계약 확정 트랜잭션이 ACTIVE로 복원한다';
