-- 계약을 매물과 독립된 이력 엔터티(property_contract)로 분리한다.
-- 배포 전 운영 DB 읽기 전용 사전 조회 결과 property·expiry_task 모두 0행이었으므로
-- 기존 데이터 보존·단계적 전환(expand/contract) 없이 옛 컬럼과 제약을 직접 교체하는
-- 클린 컷오버로 진행한다.

-- expiry_task는 새 구조에서 property_contract를 참조하도록 완전히 바뀌므로
-- 옛 테이블을 먼저 제거한다(운영 데이터 0행 확인됨).
DROP TABLE expiry_task;

-- property: 계약 기간·당사자·금액 컬럼을 제거하고 요약 상태만 남긴다.
ALTER TABLE property DROP CONSTRAINT ck_property_deal_state;
ALTER TABLE property DROP COLUMN has_contract;
ALTER TABLE property DROP COLUMN contract_expiry_date;
ALTER TABLE property DROP COLUMN landlord_name;
ALTER TABLE property DROP COLUMN landlord_phone;
ALTER TABLE property DROP COLUMN current_occupant_name;
ALTER TABLE property DROP COLUMN current_occupant_phone;

ALTER TABLE property ALTER COLUMN property_status SET DEFAULT 'NO_CONTRACT';
ALTER TABLE property ADD UNIQUE (id, office_id, deal_type);

COMMENT ON TABLE property IS '사무소가 관리하는 매물. 계약의 기간·당사자·금액과 과거 이력은 property_contract에 별도로 저장하고, 이 테이블에는 매물 자체 정보와 현재 계약의 요약 상태만 둔다';
COMMENT ON COLUMN property.property_status IS '매물 게시판용 요약 상태: ACTIVE 현재 계약 있음, NO_CONTRACT 현재 계약 없음, NEGOTIATING 전세·월세 계약 종료일이 지났으나 재계약·종료 처리가 끝나지 않아 협의 중. 계약 명령과 D-90 배치가 property_contract와 같은 트랜잭션에서 동기화하며 일반 매물 수정 API로 직접 변경하지 않는다';

-- property_contract: 매매·전세·월세 계약의 현재 상태와 과거 이력을 계약별 행으로 보존한다.
CREATE TABLE property_contract (
    id                       BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    office_id                BIGINT       NOT NULL,
    property_id              BIGINT       NOT NULL,
    deal_type                VARCHAR(10)  NOT NULL CHECK (deal_type IN ('SALE','JEONSE','MONTHLY')),
    previous_contract_id     BIGINT,
    created_by_member_id     BIGINT       NOT NULL,
    status                   VARCHAR(15)  NOT NULL DEFAULT 'ACTIVE'
                                           CHECK (status IN ('ACTIVE','COMPLETED','TERMINATED','RENEWED','CANCELLED')),
    contract_start_date      DATE         NOT NULL,
    contract_end_date        DATE,
    owner_party_name         VARCHAR(50)  NOT NULL,
    owner_party_phone        VARCHAR(20)  NOT NULL,
    counterparty_name        VARCHAR(50)  NOT NULL,
    counterparty_phone       VARCHAR(20)  NOT NULL,
    sale_price               BIGINT,
    deposit_amount           BIGINT,
    monthly_rent_amount      BIGINT,
    ended_at                 TIMESTAMPTZ,
    end_reason               VARCHAR(500),
    created_at               TIMESTAMPTZ  NOT NULL DEFAULT now(),
    updated_at               TIMESTAMPTZ  NOT NULL,
    UNIQUE (id, office_id, property_id),
    UNIQUE (id, office_id, property_id, deal_type)
);

ALTER TABLE property_contract
    ADD CONSTRAINT fk_property_contract_property_office_type
    FOREIGN KEY (property_id, office_id, deal_type)
    REFERENCES property (id, office_id, deal_type)
    ON DELETE RESTRICT;

ALTER TABLE property_contract
    ADD CONSTRAINT fk_property_contract_previous_same_property
    FOREIGN KEY (previous_contract_id, office_id, property_id)
    REFERENCES property_contract (id, office_id, property_id)
    ON DELETE RESTRICT;

ALTER TABLE property_contract
    ADD CONSTRAINT fk_property_contract_created_by_membership
    FOREIGN KEY (created_by_member_id, office_id)
    REFERENCES office_membership (member_id, office_id)
    ON DELETE RESTRICT;

ALTER TABLE property_contract ADD CONSTRAINT ck_property_contract_previous_not_self
    CHECK (previous_contract_id IS NULL OR previous_contract_id <> id);

ALTER TABLE property_contract ADD CONSTRAINT ck_property_contract_period CHECK (
    (deal_type = 'SALE' AND contract_end_date IS NULL)
    OR (deal_type IN ('JEONSE','MONTHLY') AND contract_end_date IS NOT NULL
        AND contract_end_date >= contract_start_date)
);

ALTER TABLE property_contract ADD CONSTRAINT ck_property_contract_amounts CHECK (
    (deal_type = 'SALE' AND sale_price IS NOT NULL AND sale_price >= 0
        AND deposit_amount IS NULL AND monthly_rent_amount IS NULL)
    OR (deal_type = 'JEONSE' AND sale_price IS NULL
        AND deposit_amount IS NOT NULL AND deposit_amount >= 0 AND monthly_rent_amount IS NULL)
    OR (deal_type = 'MONTHLY' AND sale_price IS NULL
        AND deposit_amount IS NOT NULL AND deposit_amount >= 0
        AND monthly_rent_amount IS NOT NULL AND monthly_rent_amount >= 0)
);

ALTER TABLE property_contract ADD CONSTRAINT ck_property_contract_status_fields CHECK (
    (status = 'ACTIVE' AND ended_at IS NULL AND end_reason IS NULL)
    OR (status IN ('COMPLETED','RENEWED') AND ended_at IS NOT NULL AND end_reason IS NULL)
    OR (status IN ('TERMINATED','CANCELLED') AND ended_at IS NOT NULL AND end_reason IS NOT NULL)
);

CREATE UNIQUE INDEX uq_property_contract_active
    ON property_contract (property_id) WHERE status = 'ACTIVE';
CREATE UNIQUE INDEX uq_property_contract_previous
    ON property_contract (previous_contract_id) WHERE previous_contract_id IS NOT NULL;
CREATE INDEX ix_property_contract_office_status_start
    ON property_contract (office_id, status, contract_start_date DESC);
CREATE INDEX ix_property_contract_property_created
    ON property_contract (property_id, created_at DESC);

COMMENT ON TABLE property_contract IS '매매·전세·월세 계약의 현재 상태와 과거 이력을 계약별 행으로 보존한다. 재계약은 기존 행을 덮어쓰지 않고 새 행을 생성하며 previous_contract_id로 직전 계약을 연결한다';
COMMENT ON COLUMN property_contract.id IS '계약 내부 식별자';
COMMENT ON COLUMN property_contract.office_id IS '계약을 관리하는 사무소. property_id·deal_type과 함께 매물의 사무소·거래유형 일치를 복합 외래 키로 검증';
COMMENT ON COLUMN property_contract.property_id IS '계약 대상 매물';
COMMENT ON COLUMN property_contract.deal_type IS '계약 유형: SALE 매매, JEONSE 전세, MONTHLY 월세. 대상 매물의 거래 유형과 같아야 한다';
COMMENT ON COLUMN property_contract.previous_contract_id IS '재계약으로 생성된 새 계약이 가리키는 직전 계약. 같은 사무소·매물의 계약만 참조하며 하나의 이전 계약에서 새 계약 하나만 파생될 수 있다';
COMMENT ON COLUMN property_contract.created_by_member_id IS '계약을 등록한 승인된 사무소 구성원';
COMMENT ON COLUMN property_contract.status IS '계약 상태: ACTIVE 계약 중, COMPLETED 정상 종료, TERMINATED 중도 종료, RENEWED 재계약으로 종료, CANCELLED 계약 취소';
COMMENT ON COLUMN property_contract.contract_start_date IS '계약 시작일';
COMMENT ON COLUMN property_contract.contract_end_date IS '계약 종료 예정일. 전세·월세는 필수이고 매매는 NULL이며 전세·월세 D-90 업무의 기준일';
COMMENT ON COLUMN property_contract.owner_party_name IS '매도인·임대인 이름. SALE이면 매도인, JEONSE·MONTHLY이면 임대인';
COMMENT ON COLUMN property_contract.owner_party_phone IS '매도인·임대인 연락처. SALE이면 매도인, JEONSE·MONTHLY이면 임대인';
COMMENT ON COLUMN property_contract.counterparty_name IS '매수인·임차인 이름. SALE이면 매수인, JEONSE·MONTHLY이면 임차인';
COMMENT ON COLUMN property_contract.counterparty_phone IS '매수인·임차인 연락처. SALE이면 매수인, JEONSE·MONTHLY이면 임차인';
COMMENT ON COLUMN property_contract.sale_price IS '매매가(원 단위). SALE에서만 필수';
COMMENT ON COLUMN property_contract.deposit_amount IS '보증금(원 단위). JEONSE·MONTHLY에서 필수';
COMMENT ON COLUMN property_contract.monthly_rent_amount IS '월세(원 단위). MONTHLY에서만 필수';
COMMENT ON COLUMN property_contract.ended_at IS '정상 종료·중도 종료·재계약 종료·취소 처리 일시';
COMMENT ON COLUMN property_contract.end_reason IS '중도 종료 또는 계약 취소 사유. TERMINATED·CANCELLED에서 필수';
COMMENT ON COLUMN property_contract.created_at IS '계약 등록 일시';
COMMENT ON COLUMN property_contract.updated_at IS '계약 마지막 수정 일시';

-- expiry_task: 계약 기준 복합 FK로 재구성한 D-90 계약 후속 업무. 전세·월세에만 생성한다.
CREATE TABLE expiry_task (
    id                     BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    office_id               BIGINT      NOT NULL,
    property_id             BIGINT      NOT NULL,
    property_contract_id    BIGINT      NOT NULL,
    deal_type               VARCHAR(10) NOT NULL CHECK (deal_type IN ('JEONSE','MONTHLY')),
    task_type               VARCHAR(10) NOT NULL DEFAULT 'D90',
    contract_end_date       DATE        NOT NULL,
    target_date             DATE        NOT NULL,
    status                  VARCHAR(10) NOT NULL DEFAULT 'OPEN' CHECK (status IN ('OPEN','COMPLETED','CANCELLED')),
    created_at              TIMESTAMPTZ NOT NULL DEFAULT now(),
    completed_at            TIMESTAMPTZ,
    cancelled_at            TIMESTAMPTZ,
    cancel_reason           VARCHAR(30) CHECK (cancel_reason IS NULL OR cancel_reason IN ('PROPERTY_SOFT_DELETED','CONTRACT_COMPLETED','CONTRACT_TERMINATED','CONTRACT_RENEWED','CONTRACT_CANCELLED')),
    UNIQUE (property_contract_id, task_type)
);

ALTER TABLE expiry_task
    ADD CONSTRAINT fk_expiry_task_contract_office_property
    FOREIGN KEY (property_contract_id, office_id, property_id, deal_type)
    REFERENCES property_contract (id, office_id, property_id, deal_type)
    ON DELETE RESTRICT;

ALTER TABLE expiry_task
    ADD CONSTRAINT ck_expiry_task_target_date
    CHECK (target_date = contract_end_date - 90);

ALTER TABLE expiry_task ADD CONSTRAINT ck_expiry_task_type CHECK (task_type = 'D90');

ALTER TABLE expiry_task ADD CONSTRAINT ck_expiry_task_status CHECK (
    (status = 'OPEN' AND completed_at IS NULL AND cancelled_at IS NULL AND cancel_reason IS NULL)
    OR (status = 'COMPLETED' AND completed_at IS NOT NULL AND cancelled_at IS NULL AND cancel_reason IS NULL)
    OR (status = 'CANCELLED' AND completed_at IS NULL AND cancelled_at IS NOT NULL AND cancel_reason IS NOT NULL)
);

CREATE INDEX ix_expiry_task_office_status_target ON expiry_task (office_id, status, target_date);

COMMENT ON TABLE expiry_task IS '전세·월세 계약 종료일 90일 전에 생성되는 고객 후속관리 업무. 매매 계약에는 생성하지 않는다';
COMMENT ON COLUMN expiry_task.id IS '업무 내부 식별자';
COMMENT ON COLUMN expiry_task.office_id IS '사무소 ID. property_contract_id·property_id와 함께 대상 계약의 사무소·매물 일치를 복합 외래 키로 검증';
COMMENT ON COLUMN expiry_task.property_id IS '매물 ID. property_contract_id·office_id와 함께 대상 계약을 복합 외래 키로 참조';
COMMENT ON COLUMN expiry_task.property_contract_id IS 'D-90 업무의 기준이 되는 전세·월세 계약';
COMMENT ON COLUMN expiry_task.deal_type IS 'D-90 대상 계약 유형. JEONSE 전세 또는 MONTHLY 월세만 허용하며 참조 계약의 유형과 같아야 한다';
COMMENT ON COLUMN expiry_task.task_type IS '업무 종류(현재는 D90 하나로 고정)';
COMMENT ON COLUMN expiry_task.contract_end_date IS '업무 생성 시점의 계약 종료 예정일 스냅샷';
COMMENT ON COLUMN expiry_task.target_date IS '업무 처리 목표일(만기일 - 90일)';
COMMENT ON COLUMN expiry_task.status IS '업무 상태: OPEN 진행 중, COMPLETED 완료, CANCELLED 취소';
COMMENT ON COLUMN expiry_task.created_at IS '업무 생성 일시(D-90 배치가 생성)';
COMMENT ON COLUMN expiry_task.completed_at IS '업무 완료 처리 일시';
COMMENT ON COLUMN expiry_task.cancelled_at IS '업무 취소 처리 일시';
COMMENT ON COLUMN expiry_task.cancel_reason IS '취소 사유: PROPERTY_SOFT_DELETED 매물 삭제, CONTRACT_COMPLETED 정상 종료, CONTRACT_TERMINATED 중도 종료, CONTRACT_RENEWED 재계약, CONTRACT_CANCELLED 계약 취소';
