DO $$
BEGIN
    IF EXISTS (SELECT 1 FROM office WHERE real_estate_license_number IS NULL) THEN
        RAISE EXCEPTION 'V9 requires office.real_estate_license_number for every existing office';
    END IF;

    IF EXISTS (
        SELECT 1
        FROM login_identity
        WHERE revoked_at IS NULL
        GROUP BY member_id, provider
        HAVING count(*) > 1
    ) THEN
        RAISE EXCEPTION 'V9 requires at most one active login identity per member and provider';
    END IF;

    IF EXISTS (
        SELECT 1
        FROM office_membership
        WHERE status = 'PENDING'
        GROUP BY member_id
        HAVING count(*) > 1
    ) THEN
        RAISE EXCEPTION 'V9 requires at most one pending office membership per member';
    END IF;

    IF EXISTS (SELECT 1 FROM office_membership WHERE status = 'PENDING' AND role <> 'STAFF') THEN
        RAISE EXCEPTION 'V9 requires pending office memberships to use the STAFF role';
    END IF;

    IF EXISTS (SELECT 1 FROM office_membership WHERE reviewed_by_type = 'OPERATOR') THEN
        RAISE EXCEPTION 'V9 cannot map legacy operator membership reviews to an office administrator';
    END IF;

    IF EXISTS (
        SELECT 1
        FROM office_membership_status_history
        WHERE changed_by_type = 'ADMIN'
          AND changed_by_membership_id = office_membership_id
    ) THEN
        RAISE EXCEPTION 'V9 does not allow self-referential membership history';
    END IF;

    IF EXISTS (
        SELECT 1
        FROM office_registration_status_history
        WHERE changed_by_type = 'OPERATOR'
    ) THEN
        RAISE EXCEPTION 'V9 requires legacy operator registration history to be mapped before migration';
    END IF;
END
$$;

ALTER TABLE member ALTER COLUMN email DROP NOT NULL;

CREATE UNIQUE INDEX uq_login_identity_member_provider_active
    ON login_identity (member_id, provider)
    WHERE revoked_at IS NULL;

DROP TABLE email_verification_code;

ALTER TABLE oauth_transaction DROP CONSTRAINT ck_oauth_transaction_purpose_fields;
ALTER TABLE oauth_transaction DROP CONSTRAINT oauth_transaction_purpose_check;

UPDATE oauth_transaction
SET purpose = 'STEP_UP'
WHERE purpose = 'LINK';

ALTER TABLE oauth_transaction ADD CONSTRAINT oauth_transaction_purpose_check
    CHECK (purpose IN ('LOGIN','STEP_UP'));

ALTER TABLE oauth_transaction ADD CONSTRAINT ck_oauth_transaction_purpose_fields CHECK (
    (purpose = 'STEP_UP' AND member_id IS NOT NULL AND initiating_session_id IS NOT NULL)
    OR (purpose = 'LOGIN' AND member_id IS NULL AND initiating_session_id IS NULL AND step_up_verified_at IS NULL)
);

CREATE TABLE operator (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    kakao_provider_key  VARCHAR(255) NOT NULL,
    name                VARCHAR(50)  NOT NULL,
    status              VARCHAR(10)  NOT NULL DEFAULT 'ACTIVE' CHECK (status IN ('ACTIVE','DISABLED')),
    created_at          TIMESTAMPTZ  NOT NULL DEFAULT now(),
    disabled_at         TIMESTAMPTZ
);

CREATE UNIQUE INDEX uq_operator_kakao_provider_key ON operator (kakao_provider_key);

ALTER TABLE operator ADD CONSTRAINT ck_operator_status CHECK (
    (status = 'ACTIVE' AND disabled_at IS NULL)
    OR (status = 'DISABLED' AND disabled_at IS NOT NULL)
);

ALTER TABLE office ALTER COLUMN real_estate_license_number SET NOT NULL;
ALTER TABLE office ADD CONSTRAINT office_real_estate_license_number_key UNIQUE (real_estate_license_number);

ALTER TABLE office_registration DROP CONSTRAINT ck_office_registration_status;
ALTER TABLE office_registration DROP CONSTRAINT ck_office_registration_storage;
ALTER TABLE office_registration DROP CONSTRAINT office_registration_status_check;
DROP INDEX uq_office_registration_pending_bizno;
DROP INDEX uq_office_registration_pending_applicant;

ALTER TABLE office_registration
    ADD COLUMN real_estate_license_number VARCHAR(30),
    ADD COLUMN requested_office_name VARCHAR(100),
    ADD COLUMN requested_representative_name VARCHAR(50),
    ADD COLUMN requested_phone VARCHAR(20),
    ADD COLUMN requested_address_base VARCHAR(200),
    ADD COLUMN requested_address_detail VARCHAR(100),
    ADD COLUMN cancelled_at TIMESTAMPTZ,
    ADD COLUMN reapplication_started_at TIMESTAMPTZ;

UPDATE office_registration registration
SET real_estate_license_number = office.real_estate_license_number,
    requested_office_name = office.name,
    requested_representative_name = office.representative_name,
    requested_phone = office.phone,
    requested_address_base = office.address_base,
    requested_address_detail = office.address_detail
FROM office
WHERE registration.resulting_office_id = office.id;

DO $$
BEGIN
    IF EXISTS (
        SELECT 1
        FROM office_registration
        WHERE real_estate_license_number IS NULL
           OR requested_office_name IS NULL
           OR requested_representative_name IS NULL
           OR requested_phone IS NULL
           OR requested_address_base IS NULL
    ) THEN
        RAISE EXCEPTION 'V9 cannot derive required request snapshots for legacy office registrations';
    END IF;
END
$$;

UPDATE office_registration
SET status = CASE status
    WHEN 'PENDING_VERIFICATION' THEN 'PENDING_REVIEW'
    WHEN 'MANUAL_REVIEW' THEN 'EVIDENCE_REQUESTED'
    ELSE status
END;

ALTER TABLE office_registration
    ALTER COLUMN real_estate_license_number SET NOT NULL,
    ALTER COLUMN requested_office_name SET NOT NULL,
    ALTER COLUMN requested_representative_name SET NOT NULL,
    ALTER COLUMN requested_phone SET NOT NULL,
    ALTER COLUMN requested_address_base SET NOT NULL,
    ALTER COLUMN status SET DEFAULT 'PENDING_REVIEW';

ALTER TABLE office_registration ADD CONSTRAINT office_registration_status_check
    CHECK (status IN ('PENDING_REVIEW','EVIDENCE_REQUESTED','APPROVED','REJECTED','CANCELLED'));

ALTER TABLE office_registration ADD CONSTRAINT ck_office_registration_status CHECK (
    (status IN ('PENDING_REVIEW','EVIDENCE_REQUESTED')
        AND resulting_office_id IS NULL AND rejection_reason IS NULL AND reviewed_at IS NULL AND cancelled_at IS NULL
        AND reapplication_started_at IS NULL)
    OR (status = 'APPROVED'
        AND resulting_office_id IS NOT NULL AND rejection_reason IS NULL AND reviewed_at IS NOT NULL AND cancelled_at IS NULL
        AND reapplication_started_at IS NULL)
    OR (status = 'REJECTED'
        AND resulting_office_id IS NULL AND rejection_reason IS NOT NULL AND reviewed_at IS NOT NULL AND cancelled_at IS NULL
        AND (reapplication_started_at IS NULL OR reapplication_started_at > reviewed_at))
    OR (status = 'CANCELLED'
        AND resulting_office_id IS NULL AND rejection_reason IS NULL AND reviewed_at IS NULL AND cancelled_at IS NOT NULL
        AND reapplication_started_at IS NULL)
);

ALTER TABLE office_registration ADD CONSTRAINT ck_office_registration_storage CHECK (
    status NOT IN ('REJECTED','CANCELLED')
    OR document_object_key IS NULL
    OR document_storage_status IN ('MOVE_PENDING','PENDING_DELETION','DELETED','MOVE_FAILED')
);

CREATE UNIQUE INDEX uq_office_registration_pending_bizno
    ON office_registration (business_registration_number)
    WHERE status IN ('PENDING_REVIEW','EVIDENCE_REQUESTED');

CREATE UNIQUE INDEX uq_office_registration_pending_applicant
    ON office_registration (applicant_member_id)
    WHERE status IN ('PENDING_REVIEW','EVIDENCE_REQUESTED');

ALTER TABLE office_registration_status_history DROP CONSTRAINT ck_reg_history_actor;
ALTER TABLE office_registration_status_history DROP CONSTRAINT office_registration_status_history_changed_by_type_check;
ALTER TABLE office_registration_status_history DROP CONSTRAINT office_registration_status_history_from_status_check;
ALTER TABLE office_registration_status_history DROP CONSTRAINT office_registration_status_history_to_status_check;

UPDATE office_registration_status_history
SET from_status = CASE from_status
        WHEN 'PENDING_VERIFICATION' THEN 'PENDING_REVIEW'
        WHEN 'MANUAL_REVIEW' THEN 'EVIDENCE_REQUESTED'
        ELSE from_status
    END,
    to_status = CASE to_status
        WHEN 'PENDING_VERIFICATION' THEN 'PENDING_REVIEW'
        WHEN 'MANUAL_REVIEW' THEN 'EVIDENCE_REQUESTED'
        ELSE to_status
    END;

ALTER TABLE office_registration_status_history
    DROP COLUMN changed_by_operator_identifier,
    ADD COLUMN changed_by_operator_id BIGINT;

ALTER TABLE office_registration_status_history ADD CONSTRAINT office_registration_status_history_from_status_check
    CHECK (from_status IS NULL OR from_status IN ('PENDING_REVIEW','EVIDENCE_REQUESTED','APPROVED','REJECTED','CANCELLED'));

ALTER TABLE office_registration_status_history ADD CONSTRAINT office_registration_status_history_to_status_check
    CHECK (to_status IN ('PENDING_REVIEW','EVIDENCE_REQUESTED','APPROVED','REJECTED','CANCELLED'));

ALTER TABLE office_registration_status_history ADD CONSTRAINT office_registration_status_history_changed_by_type_check
    CHECK (changed_by_type IN ('APPLICANT','OPERATOR','SYSTEM'));

ALTER TABLE office_registration_status_history ADD CONSTRAINT ck_reg_history_actor CHECK (
    (changed_by_type = 'OPERATOR' AND changed_by_operator_id IS NOT NULL)
    OR (changed_by_type IN ('APPLICANT','SYSTEM') AND changed_by_operator_id IS NULL)
);

ALTER TABLE office_registration_status_history
    ADD CONSTRAINT fk_reg_history_operator
    FOREIGN KEY (changed_by_operator_id)
    REFERENCES operator (id)
    ON DELETE RESTRICT;

ALTER TABLE office_membership DROP CONSTRAINT ck_office_membership_reviewer;
ALTER TABLE office_membership DROP CONSTRAINT ck_office_membership_status;
ALTER TABLE office_membership DROP CONSTRAINT office_membership_reviewed_by_type_check;
ALTER TABLE office_membership DROP CONSTRAINT office_membership_status_check;

ALTER TABLE office_membership
    DROP COLUMN reviewed_by_operator_identifier,
    ADD COLUMN cancelled_at TIMESTAMPTZ,
    ADD COLUMN reapplication_started_at TIMESTAMPTZ;

ALTER TABLE office_membership ADD CONSTRAINT office_membership_reviewed_by_type_check
    CHECK (reviewed_by_type IN ('ADMIN','SYSTEM'));

ALTER TABLE office_membership ADD CONSTRAINT office_membership_status_check
    CHECK (status IN ('PENDING','APPROVED','REJECTED','REVOKED','CANCELLED'));

ALTER TABLE office_membership ADD CONSTRAINT ck_office_membership_reviewer CHECK (
    reviewed_by_type IS NULL
    OR (reviewed_by_type = 'ADMIN' AND reviewed_by_membership_id IS NOT NULL)
    OR (reviewed_by_type = 'SYSTEM' AND reviewed_by_membership_id IS NULL)
);

ALTER TABLE office_membership ADD CONSTRAINT ck_office_membership_status CHECK (
    (status = 'PENDING'
        AND role = 'STAFF'
        AND reviewed_at IS NULL AND reviewed_by_type IS NULL AND reviewed_by_membership_id IS NULL
        AND rejection_reason IS NULL AND revoked_at IS NULL AND revocation_reason IS NULL
        AND cancelled_at IS NULL AND reapplication_started_at IS NULL)
    OR (status = 'APPROVED'
        AND reviewed_at IS NOT NULL AND reviewed_by_type IS NOT NULL
        AND rejection_reason IS NULL AND revoked_at IS NULL AND revocation_reason IS NULL
        AND cancelled_at IS NULL AND reapplication_started_at IS NULL)
    OR (status = 'REJECTED'
        AND reviewed_at IS NOT NULL AND reviewed_by_type IS NOT NULL
        AND rejection_reason IS NOT NULL AND revoked_at IS NULL AND revocation_reason IS NULL
        AND cancelled_at IS NULL
        AND (reapplication_started_at IS NULL OR reapplication_started_at > reviewed_at))
    OR (status = 'REVOKED'
        AND reviewed_at IS NOT NULL AND reviewed_by_type IS NOT NULL
        AND rejection_reason IS NULL AND revoked_at IS NOT NULL AND revocation_reason IS NOT NULL
        AND cancelled_at IS NULL AND reapplication_started_at IS NULL)
    OR (status = 'CANCELLED'
        AND reviewed_at IS NULL AND reviewed_by_type IS NULL AND reviewed_by_membership_id IS NULL
        AND rejection_reason IS NULL AND revoked_at IS NULL AND revocation_reason IS NULL
        AND cancelled_at IS NOT NULL AND reapplication_started_at IS NULL)
);

CREATE UNIQUE INDEX uq_office_membership_member_pending
    ON office_membership (member_id)
    WHERE status = 'PENDING';

ALTER TABLE office_membership_status_history DROP CONSTRAINT ck_membership_history_actor;
ALTER TABLE office_membership_status_history DROP CONSTRAINT office_membership_status_history_from_status_check;
ALTER TABLE office_membership_status_history DROP CONSTRAINT office_membership_status_history_to_status_check;

ALTER TABLE office_membership_status_history ADD CONSTRAINT office_membership_status_history_from_status_check
    CHECK (from_status IS NULL OR from_status IN ('PENDING','APPROVED','REJECTED','REVOKED','CANCELLED'));

ALTER TABLE office_membership_status_history ADD CONSTRAINT office_membership_status_history_to_status_check
    CHECK (to_status IN ('PENDING','APPROVED','REJECTED','REVOKED','CANCELLED'));

ALTER TABLE office_membership_status_history ADD CONSTRAINT ck_membership_history_actor CHECK (
    (changed_by_type = 'ADMIN'
        AND changed_by_membership_id IS NOT NULL
        AND changed_by_membership_id <> office_membership_id)
    OR (changed_by_type IN ('APPLICANT','SYSTEM') AND changed_by_membership_id IS NULL)
);

ALTER TABLE property ADD COLUMN archived_at TIMESTAMPTZ;

CREATE INDEX ix_property_archived
    ON property (office_id, archived_at)
    WHERE deleted_at IS NULL;

ALTER TABLE property_contract ADD CONSTRAINT ck_property_contract_status_by_deal_type CHECK (
    deal_type <> 'SALE' OR status NOT IN ('RENEWED','TERMINATED')
);

COMMENT ON COLUMN member.email IS '향후 이메일 로그인·알림 확장용 nullable 컬럼. 1차MVP(카카오 전용 가입)는 API·화면 미사용';
COMMENT ON TABLE oauth_transaction IS '카카오 OAuth 인가~콜백 왕복 상태. state는 순수 난수이고 의미는 이 테이블에만 있다(LOGIN/STEP_UP 구분, STEP_UP 대상 회원 등)';
COMMENT ON COLUMN oauth_transaction.purpose IS '목적: LOGIN 로그인/가입, STEP_UP 기존 회원의 재인증(사업자정보 변경·회원탈퇴)';
COMMENT ON TABLE office_registration IS '신규 사무소 등록 신청. 신청자가 제출한 사무소 정보는 심사 대상 스냅샷으로 보관하고 승인 시 운영자가 확정한 값으로 office를 생성한다. 자동 승인 경로는 없다';
COMMENT ON COLUMN office_registration.status IS '심사 상태: PENDING_REVIEW 심사 대기, EVIDENCE_REQUESTED 증빙 요청, APPROVED 승인, REJECTED 반려, CANCELLED 신청자 취소';
COMMENT ON TABLE office_membership IS '사무소 소속과 관리자·직원 권한. 회원별 APPROVED 소속은 최대 하나다';
COMMENT ON COLUMN office_membership.status IS '소속 상태: PENDING 승인대기, APPROVED 승인, REJECTED 거절, REVOKED 회수, CANCELLED 신청자 취소';
COMMENT ON COLUMN property.archived_at IS '매매 거래완료 매물의 보관 전환 시각. NULL이면 활성 매물이며 보관 여부는 property_status와 독립이다';
COMMENT ON TABLE operator IS '사이로팀 운영자 로그인 계정. member와 office_membership에서 분리되며 사무소 소속이 없다';
COMMENT ON COLUMN operator.kakao_provider_key IS '운영자 로그인을 허용할 카카오 고유 회원번호';
